#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Neal's Notes
author: Neal C
description: Drawing and seeing
page_excerpts: true
url: https://nealchau.github.io
sass:
  style: compressed
