#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Neal's Notes
author: Neal C
description: Drawing and seeing
page_excerpts: true
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
url: https://nealchau.github.io
sass:
  style: compressed
